### ISSUE TITLE
Problem with fexist

### ISSUE THREAD

**Issue by coool9** [openmultiplayer/open.mp#941] opened 2024-07-27 11:54 UTC
**Describe the bug**
I tried to use open.mp. I had an old amx that works well with sa-mp server but with open.mp it was crashing the server then I used crashdetect to see some error coming from fexist then I created a new file using qawno and used the fexist function but got the same result of crashing the server.

**To Reproduce**
Create a new gm, use fexist function, compile and then run.

**Screenshots and/or logs**
`Starting open.mp server (1.2.0.2670) from commit 41ebf182bf73dc9cb11841bfe6b0179ba31f9dd5
Loading component Actors.dll
	Successfully loaded component Actors (1.2.0.2670) with UID `c81ca021eae2ad5c
Loading component Checkpoints.dll
	Successfully loaded component Checkpoints (1.2.0.2670) with UID 44a937350d611dde
Loading component Classes.dll
	Successfully loaded component Classes (1.2.0.2670) with UID 8cfb3183976da208
Loading component Console.dll
	Successfully loaded component Console (1.2.0.2670) with UID bfa24e49d0c95ee4
Loading component CustomModels.dll
	Successfully loaded component CustomModels (1.2.0.2670) with UID 15e3cb1e7c77ffff
Loading component Databases.dll
	Successfully loaded component Databases (1.2.0.2670) with UID 80092e7eb5821a96
Loading component Dialogs.dll
	Successfully loaded component Dialogs (1.2.0.2670) with UID 44a111350d611dde
Loading component GangZones.dll
	Successfully loaded component GangZones (1.2.0.2670) with UID b3351d11ee8d8056
Loading component LegacyConfig.dll
	Successfully loaded component LegacyConfig (1.2.0.2670) with UID 24ef6216838f9ffc
Loading component LegacyNetwork.dll
	Successfully loaded component RakNetLegacyNetwork (1.2.0.2670) with UID ea9799fd79cf8442
Loading component Menus.dll
	Successfully loaded component Menus (1.2.0.2670) with UID 621e219eb97ee0b2
Loading component Objects.dll
	Successfully loaded component Objects (1.2.0.2670) with UID 59f8415f72da6160
Loading component Pawn.dll
	Successfully loaded component Pawn (1.2.0.2670) with UID 78906cd9f19c36a6
Loading component Pickups.dll
	Successfully loaded component Pickups (1.2.0.2670) with UID cf304faa363dd971
Loading component Recordings.dll
	Successfully loaded component Recordings (1.2.0.2670) with UID 871144d399f5f613
Loading component TextDraws.dll
	Successfully loaded component TextDraws (1.2.0.2670) with UID 9b5dc2b1d15c992a
Loading component TextLabels.dll
	Successfully loaded component TextLabels (1.2.0.2670) with UID a0c57ea80a009742
Loading component Timers.dll
	Successfully loaded component Timers (1.2.0.2670) with UID 2ad8124c5ea257a3
Loading component Unicode.dll
	Successfully loaded component Unicode (1.2.0.2670) with UID 8ffb446f8353922b
Loading component Variables.dll
	Successfully loaded component Variables (1.2.0.2670) with UID 75e121848bc01fa2
Loading component Vehicles.dll
	Successfully loaded component Vehicles (1.2.0.2670) with UID 3f1f62ee9e22ab19
Loaded 21 component(s) from F:\OMPServer\Server\components
[2024-07-27T16:45:17+0500] [Info] Loading plugin: crashdetect
[2024-07-27T16:45:17+0500] [Info]   CrashDetect v4.10 is OK.
[2024-07-27T16:45:17+0500] [Warning] Tried to register native which is already registered: fexist
[2024-07-27T16:45:17+0500] [Info] [debug] Server crashed while executing mygm.amx
[2024-07-27T16:45:17+0500] [Info] [debug] AMX backtrace:
[2024-07-27T16:45:17+0500] [Info] [debug] #0 native fexist () [056c4804] from amxFile.dll
[2024-07-27T16:45:17+0500] [Info] [debug] #1 0000023c in public OnGameModeInit () at F:\OMPServer\Server\gamemodes\mygm.pwn:25
[2024-07-27T16:45:17+0500] [Info] [debug] System backtrace:
[2024-07-27T16:45:17+0500] [Info] [debug] #0 056c4821 in ?? () from f:\Pawn\bin\amxFile.dll
[2024-07-27T16:45:17+0500] [Info] [debug] #1 6bed2b3c in ?? () from F:\OMPServer\Server\components\Pawn.dll
[2024-07-27T16:45:17+0500] [Info] [debug] #2 6bd0340a in ?? () from F:\OMPServer\Server\plugins\crashdetect.DLL
[2024-07-27T16:45:17+0500] [Info] [debug] #3 6bd05aa6 in ?? () from F:\OMPServer\Server\plugins\crashdetect.DLL
[2024-07-27T16:45:17+0500] [Info] [debug] #4 6bcfd621 in ?? () from F:\OMPServer\Server\plugins\crashdetect.DLL
[2024-07-27T16:45:17+0500] [Info] [debug] #5 6bd0345a in ?? () from F:\OMPServer\Server\plugins\crashdetect.DLL
[2024-07-27T16:45:17+0500] [Info] [debug] #6 6be6b661 in ?? () from F:\OMPServer\Server\components\Pawn.dll
[2024-07-27T16:45:17+0500] [Info] [debug] #7 6be59d7f in ?? () from F:\OMPServer\Server\components\Pawn.dll
[2024-07-27T16:45:17+0500] [Info] [debug] #8 6be63003 in ?? () from F:\OMPServer\Server\components\Pawn.dll`

**Release version**
can be seen in the logs above. open.mp server (1.2.0.2670) from commit 41ebf182bf73dc9cb11841bfe6b0179ba31f9dd5

**Comment by AmyrAhmady** [comment] 2024-07-27 12:40
The problem isn't with open.mp; it's from the fact that you have a custom pawn (custom as in different to what omp and samp use) installed on your computer in F:/Pawn
Remove that because open.mp's pawn implementation can look for user installed pawn binaries and use them


This probably should be handled by us anyway, but I'm giving information and a solution for you to use it for now

**Comment by AmyrAhmady** [comment] 2024-09-25 05:47
Fixed in nightly, available officially in next release.

**Closed as completed** 2024-09-25 05:46 UTC
Labels: bug
