### ISSUE TITLE
[BEHAVIOR DIFFERENCE]: OnPlayerDeath

### ISSUE THREAD

**Issue by AbdulOmarCR** [openmultiplayer/open.mp#582] opened 2022-09-10 21:14 UTC
# Description
*In SAMP when OnPlayerDeath calls OnPlayerRequestSpawn(playerid), but in omp it calls OnPlayerRequestClass, so i just had to move my code from OnPlayerRequestSpawn to OnPlayerRequestClass*

#How to reproduce:
*1- debug OnPlayerDeath, OnPlayerRequestSpawn and OnPlayerRequestClass.*

# open.mp server version
*build 10*

# Operating system or distribution
*windows and linux*

# Contact information
*Baul#0343*

**Comment by AmyrAhmady** [comment] 2023-06-11 23:25
MCVE wasn't provided and I am not able to reproduce this issue, closing it now, and if you think this still happens, create a new issue with a working MCVE to test and debug.

**Closed by AmyrAhmady** 2023-06-11 23:25 UTC
